In [1]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D

In [2]:
#loading data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
#reshaping
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], X_train.shape[2], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], X_test.shape[2], 1)

In [4]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [9]:
X_train = X_train/255
X_test = X_test/255

In [10]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [12]:
#represent images
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [15]:
model = Sequential()

In [16]:
model.add(Conv2D(32, (3, 3), input_shape=(28, 28, 1), activation='relu'))

In [18]:
model.add(MaxPooling2D(2, 2))

In [19]:
model.add(Flatten())
model.add(Dense(100, activation='relu'))

In [20]:
model.add(Dense(10, activation='softmax'))

In [21]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 33s 17ms/step - loss: 0.2016 - accuracy: 0.9399
Epoch 2/10
1875/1875 [==============================] - 29s 15ms/step - loss: 0.0731 - accuracy: 0.9774
Epoch 3/10
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0512 - accuracy: 0.9837
Epoch 4/10
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0411 - accuracy: 0.9876
Epoch 5/10
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0327 - accuracy: 0.9901
Epoch 6/10
1875/1875 [==============================] - 29s 15ms/step - loss: 0.0258 - accuracy: 0.9916
Epoch 7/10
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0211 - accuracy: 0.9933
Epoch 8/10
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0164 - accuracy: 0.9948
Epoch 9/10
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0137 - accuracy: 0.9956
Epoch 10/10
1875/1875 [==============================] - 27s 15m

In [23]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 5ms/step - loss: 0.0388 - accuracy: 0.9890


[0.038779404014348984, 0.9890000224113464]